### ISSUE TITLE
Add cdn registrations for Overcloud node

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#288]
Dear Yair Fried,

I kindly request you add cdn registrations for Overcloud nodes. So that I could register my registrations with subscription.rhn.redhat.com and pull packages from redhat portal.
Also enable necessary repo in Ansible playbook for installing RedHat OpenStack on OverCloud like how you enabled in undercloud node.

**Comment by yfried** [comment]
Hi,
I would like to talk to you about this. Are you available on IRC? Could you please join our channel on Freenode (#infrared)?

**Comment by yfried** [comment]
Hi, 
According to [official documentation](https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/11/html/advanced_overcloud_customization/sect-registering_the_overcloud) you should be able to register your machines on deployment using `--overcloud-templates` [feature](http://infrared.readthedocs.io/en/latest/tripleo-overcloud.html#overcloud-options):


1. create a file `overcloud_cdn.yml`:
    ```yaml
      ---
      tripleo_heat_templates:
          - /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_deploy/rhel-registration/rhel-registration-resource-registry.yaml
          - /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_deploy/rhel-registration/environment-rhel-registration.yaml
      
      custom_templates:
        parameter_defaults:
            rhel_reg_auto_attach: ""
            rhel_reg_activation_key: "my-openstack"
            rhel_reg_org: "1234567"
            rhel_reg_pool_id: "1a85f9223e3d5e43013e3d6e8ff506fd"
            rhel_reg_repos: "rhel-7-server-rpms rhel-7-server-extras-rpms rhel-7-server-rh-common-rpms rhel-ha-for-rhel-7-server-rpms rhel-7-server-openstack-11-rpms rhel-7-server-rhceph-2-osd-rpms rhel-7-server-rhceph-2-mon-rpms"
      ...
    ```
    Note that you only need to add the fields you wish to override (the rest should be included)

2. Include add the file in the deploy command:
    ```
    infrared tripleo-overcloud ... --deploy yes --overcloud-templates overcloud_cdn.yml
    ```
